# NOTE: this should probably be installed
# - name: Add overlay and br_netfilter module
#   community.general.modprobe:
#     name: "{{item}}"
#     state: present
#   loop:
#     - overlay
#     - br_netfilter
#
# - name: set overlay and br_netfilter
#   ansible.builtin.shell: |
#     cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
#     overlay
#     br_netfilter
#     EOF
#
# - name: configure requred sysctl to persist across system reboots
#   ansible.builtin.shell: |
#     cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
#     net.bridge.bridge-nf-call-iptables  = 1
#     net.ipv4.ip_forward                 = 1
#     net.bridge.bridge-nf-call-ip6tables = 1
#     EOF

# sudo sysctl --system
- name: apply sysctl parameters without reboot to current environment
  shell: sysctl --system
  become: true

# - name: create containerd dir if it does not exist
#   shell: sudo mkdir -p /etc/containerd
#
# - name: create default config file for containerd
#   shell: containerd config default | tee /etc/containerd/config.toml
#   become: true
#
# - name: turn on systemd C group in containerd config file
#   shell: sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
#   become: true

- name: Remove Containerd config file
  file:
    state: absent
    path: /etc/containerd/config.toml
  become: true

# shell: sudo systemctl restart containerd;
- name: restart containerd
  ansible.builtin.systemd:
    state: restarted
    name: containerd
  become: true
