- name: Start Cluster
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  # register: output
  become: true


- name: Add .kube directory
  ansible.builtin.file:
    path: "/home/{{home_dir}}/.kube"
    state: directory
    mode: '0777'

# TODO: make this ansible way
# - name: Copy kubernetes admin file
#   shell: "cp -i /etc/kubernetes/admin.conf /home/{{home_dir}}/.kube/config"
#   become: true

# sudo cp -i /etc/kubernetes/admin.conf /home/{{home_dir}}/.kube/config
- name: Copy kubernetes admin file
  copy:
    src: "/etc/kubernetes/admin.conf"
    remote_src: true
    dest: "/home/{{home_dir}}/.kube/config"
    mode: '0777'
  become: true


# # TODO: make this ansible way
# - name: change .kube permissions
#   shell: "chown $(id -u):$(id -g) /home/{{home_dir}}/.kube/config"
#   become: true

# https://stackoverflow.com/questions/57070583/using-chown-command-in-ansible
# sudo chown $(id -u):$(id -g) $HOME/.kube/config"
- name: Change ~/kube/config file permission
  file:
    path: "/home/{{home_dir}}/.kube/config"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
  become: true

- name: "Networking Calico 1"
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

- name: "Networking Calico 2"
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml

- name: "Get cluster join command"
  shell: "kubeadm token create --print-join-command"
  register: cluster_join_command

- name: Storing join command in ./cluster_join_command locally
  local_action: copy content={{cluster_join_command.stdout}} dest=cluster_join_command.sh
