- name: Touch docker daemon config
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    state: touch
    mode: '0777'
  become: true

- name: Remove any previous docker daemon configuration
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    state: absent
    regexp: '\{\"insecure-registries\": \[\"\d{1,3}\.\d{1,3}\.\d{1,3}\d.\d{1,3}\:5000\"\]}'
  become: true

- name: Configure docker daemon
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    state: present
    line: '\{"insecure-registries": ["{{k8_master_public_ip}}"]\}'
  become: true

- name: Create /etc/containerd directory if it exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  become: true

- name: create default config file for containerd (which will replace old)
  shell: containerd config default | tee /etc/containerd/config.toml
  become: true

- name: Add configuration to /etc/containerd/config.toml file
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    insertafter: '      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]'
    line: '      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{k8_master_public_ip}}:5000"]\n        endpoint = [{{k8_master_public_ip}}:5000]'
  become: true

- name: restart containerd and docker
  ansible.builtin.systemd:
    state: restarted
    name: "{{item}}"
  become: true
  loop:
    - containerd
    - docker

- name: Create docker registry
  shell: docker run -d -p 5000:5000 --restart=always --name registry registry:2
  ignore_errors: true
