services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile_server
    network_mode: host
  client:
    build:
      context: ./
      dockerfile: Dockerfile_client
    network_mode: host
    depends_on:
      - server
