---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tcp-server
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Cluster
...
